### ISSUE TITLE
spark  3.0.1 的版本问题

### ISSUE THREAD

**Issue by tian1ya** [tangchenyang/bigdata_develop_platform#1]
异常信息：
cp: cannot stat '/opt/hadoop-cluster/bigdata_develop_platform/components/spark-3.0.1/conf/spark-env.sh.template': No such file or directory
install_spark.sh: line 32: /opt/hadoop-cluster/bigdata_develop_platform/components/spark-3.0.1/conf/spark-env.sh: No such file or directory
install_spark.sh: line 33: /opt/hadoop-cluster/bigdata_develop_platform/components/spark-3.0.1/conf/spark-env.sh: No such file or directory
install_spark.sh: line 34: /opt/hadoop-cluster/bigdata_develop_platform/components/spark-3.0.1/conf/spark-env.sh: No such file or directory
install_spark.sh: line 35: /opt/hadoop-cluster/bigdata_develop_platform/components/spark-3.0.1/conf/spark-env.sh: No such file or directory
install_spark.sh: line 36: /opt/hadoop-cluster/bigdata_develop_platform/components/spark-3.0.1/conf/spark-env.sh: No such file or directory

解决：
阿里源 spark 中已经没有该版本，目前能看到的有 spark-3.0.3/spark-3.1.2/spark-2.4.8/ 三个版本，需要在配置文件中修改版本和spark 环境变量值就可以正常安装 spark了

**Comment by tangchenyang** [comment]
will install based on docker
